font:
  size: 10
  normal:
    family: Droid Sans Mono Dotted for Powerline
    style: Regular

  bold:
    family: Droid Sans Mono Dotted for Powerline

  italic:
    family: Droid Sans Mono Dotted for Powerline

schemes:
  monokai_dark: &monokai_dark
    primary:
      background: '#272822'
      foreground: '#F8F8F2'

    normal:
      black:   '#272822'
      red:     '#F92672'
      green:   '#A6E22E'
      yellow:  '#F4BF75'
      blue:    '#66D9EF'
      magenta: '#AE81FF'
      cyan:    '#A1EFE4'
      white:   '#F8F8F2'

    bright:
      black:   '#75715E'
      red:     '#F92672'
      green:   '#A6E22E'
      yellow:  '#F4BF75'
      blue:    '#66D9EF'
      magenta: '#AE81FF'
      cyan:    '#A1EFE4'
      white:   '#F9F8F5'

  monokai_pro: &monokai_pro
    primary:
      background: '#2D2A2E'
      foreground: '#FCFCFA'

    normal:
      black:   '#403E41'
      red:     '#FF6188'
      green:   '#A9DC76'
      yellow:  '#FFD866'
      blue:    '#FC9867'
      magenta: '#AB9DF2'
      cyan:    '#78DCE8'
      white:   '#FCFCFA'

    bright:
      black:   '#727072'
      red:     '#FF6188'
      green:   '#A9DC76'
      yellow:  '#FFD866'
      blue:    '#FC9867'
      magenta: '#AB9DF2'
      cyan:    '#78DCE8'
      white:   '#FCFCFA'

  solarized_light: &solarized_light
    primary:
      background: '#fdf6e3' # base3
      foreground: '#657b83' # base00

    cursor:
      text:   '#fdf6e3' # base3
      cursor: '#657b83' # base00

    normal:
      black:   '#073642' # base02
      red:     '#dc322f' # red
      green:   '#859900' # green
      yellow:  '#b58900' # yellow
      blue:    '#268bd2' # blue
      magenta: '#d33682' # magenta
      cyan:    '#2aa198' # cyan
      white:   '#eee8d5' # base2

    bright:
      black:   '#002b36' # base03
      red:     '#cb4b16' # orange
      green:   '#586e75' # base01
      yellow:  '#657b83' # base00
      blue:    '#839496' # base0
      magenta: '#6c71c4' # violet
      cyan:    '#93a1a1' # base1
      white:   '#fdf6e3' # base3

colors: *monokai_pro
