{:user {:plugins [;[lein-nodisassemble "0.1.2"]
                  [cider/cider-nrepl "0.10.2"]
                  [cider/cider-nrepl "0.9.0-SNAPSHOT"]
                  [com.gfredericks/corncob-cigar "0.1.5"]
                  [com.palletops/lein-shorthand "0.4.0"]
                  [jonase/eastwood "0.1.4"]
                  [lein-exec "0.3.4"]
                  [lein-gorilla "0.3.3"]
                  [lein-kibit "0.1.2"]
                  [lein-lein "0.2.0"]
                  [lein-oneoff "0.3.2"]
                  [lein-pprint "1.1.2"]
                  [lein-try "0.4.3"]]
        :dependencies [[robert/hooke "1.3.0"]
                       [com.gfredericks/repl-utils "0.2.6"]
                       [criterium "0.4.3"]
                       [org.clojure/tools.nrepl "0.2.8"]
                       [org.clojure/tools.namespace "0.2.10"]
                       [slamhound "1.5.5"]]
        :repl-options {:init (require '[criterium.core :as crit])}}}
